{% set name = "wbgapi" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 338c3c768bd120b80596b48fa0449ecabc93513ac989c55671dce579dbb3a5be

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - requests
    - PyYAML
    - tabulate
  run:
    - python >={{ python_min }}
    - requests
    - PyYAML
    - tabulate

test:
  imports:
    - wbgapi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tgherzog/wbgapi
  summary: wbgapi provides a comprehensive interface to the World Banks data and metadata APIs
  description: |
    WBGAPI provides modern, pythonic access to the World Banks data API. 
    It is designed both for data novices and data scientist types.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/tgherzog/wbgapi

extra:
  recipe-maintainers:
    - NejcHirci
